<a href="https://colab.research.google.com/github/GitDaksh/CS229/blob/main/ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install google-ml-edu==0.1.3 \
  keras~=3.8.0 \
  matplotlib~=3.10.0 \
  numpy~=2.0.0 \
  pandas~=2.2.0 \
  tensorflow~=2.18.0

print('installation successfull')

In [2]:
import numpy as np
import pandas as pd

# machine learning
import keras
import ml_edu.experiment
import ml_edu.results

# data visualization
import plotly.express as px

In [3]:
chicago_taxi_dataset = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/chicago_taxi_train.csv")

In [6]:
training_df = chicago_taxi_dataset.loc[:, ('TRIP_MILES', 'TRIP_SECONDS', 'FARE', 'COMPANY', 'PAYMENT_TYPE', 'TIP_RATE')]

print('Read dataset completed successfully.')

print('Total number of rows: {0}\n\n'.format(len(training_df.index)))

print(training_df.head(200))

Read dataset completed successfully.
Total number of rows: 31694


     TRIP_MILES  TRIP_SECONDS   FARE                       COMPANY  \
0          2.57          2341  31.99                     Flash Cab
1          1.18          1074   9.75                     Flash Cab
2          1.29          1173  10.25                      Sun Taxi
3          3.70          3360  23.75       Choice Taxi Association
4          1.15          1044  10.00                     Flash Cab
..          ...           ...    ...                           ...
195        1.13           821   9.00  Blue Ribbon Taxi Association
196        0.57           414   6.00                     Flash Cab
197        1.22           886   9.00                  City Service
198        1.68          1219   9.00                      Sun Taxi
199        0.71           515   6.50                      Sun Taxi

    PAYMENT_TYPE  TIP_RATE
0         Mobile       6.3
1    Credit Card      27.9
2           Cash       0.0
3           Cash       0.0
4           Cash       0.0
..           ...       ...
195       Mobile      22.9
196         Cash       0.0
197         Cash       0.0
198       Mobile      23.0
199  Credit Card      18.2

[200 rows x 6 columns]

In [5]:
print('Total number of rows: {0}\n\n'.format(len(training_df. index)))

training_df.describe(include='all')

Total number of rows: 31694

,TRIP_MILES,TRIP_SECONDS,FARE,COMPANY,PAYMENT_TYPE,TIP_RATE
count,31694.000000,31694.000000,31694.000000,31694,31694,31694.000000
unique,NaN,NaN,NaN,31,7,NaN
top,NaN,NaN,NaN,Flash Cab,Credit Card,NaN
freq,NaN,NaN,NaN,7887,14142,NaN
mean,8.289463,1319.796397,23.905210,NaN,NaN,12.965785
std,7.265672,928.932873,16.970022,NaN,NaN,15.517765
min,0.500000,60.000000,3.250000,NaN,NaN,0.000000
25%,1.720000,548.000000,9.000000,NaN,NaN,0.000000
50%,5.920000,1081.000000,18.750000,NaN,NaN,12.200000
75%,14.500000,1888.000000,38.750000,NaN,NaN,20.800000
max,68.120000,7140.000000,159.250000,NaN,NaN,648.600000

In [15]:
#What is the maximum fare?
max_fare = training_df['FARE'].max()
print('The maximum fare is: ${:.2f}'.format(max_fare))

mean_distance = training_df['TRIP_MILES'].mean()
print('The mean distance of the whole trip is: {:.2f}'.format(mean_distance))

unique_cabs = training_df['COMPANY'].nunique()
print('Total cab companies: {:.2f}'.format(unique_cabs))

most_frequest_payment_type = training_df['PAYMENT_TYPE'].value_counts().idxmax()
print('Most frequent payment type: {}'.format(most_frequest_payment_type))

missing_values = training_df.isnull().sum().sum()
print("Are there any missing values: ", "NO" if missing_values == 0 else "YES")

The maximum fare is: $159.25
The mean distance of the whole trip is: 8.29
Total cab companies: 31.00
Most frequent payment type: Credit Card
Are there any missing values:  NO

In [16]:
training_df.corr(numeric_only=True)

              TRIP_MILES  TRIP_SECONDS      FARE  TIP_RATE
TRIP_MILES      1.000000      0.800855  0.975344 -0.049594
TRIP_SECONDS    0.800855      1.000000  0.830292 -0.084294
FARE            0.975344      0.830292  1.000000 -0.070979
TIP_RATE       -0.049594     -0.084294 -0.070979  1.000000

In [ ]:
px.scatter_matrix(training_df, dimensions=['FARE', 'TRIP_MILES', 'TRIP_SECONDS'])